-- второй этап - выполнить INSERT-ы
INSERT INTO POSITIONS (NAME) VALUES ('CEO');
INSERT INTO POSITIONS (NAME) VALUES ('CTO');
INSERT INTO POSITIONS (NAME) VALUES ('Java Developer');
INSERT INTO POSITIONS (NAME) VALUES ('Quality Engineer');
INSERT INTO POSITIONS (NAME) VALUES ('Business Analyst');
INSERT INTO POSITIONS (NAME) VALUES ('System Analyst');
INSERT INTO POSITIONS (NAME) VALUES ('System Administrator');
INSERT INTO POSITIONS (NAME) VALUES ('Database Administrator');
INSERT INTO POSITIONS (NAME) VALUES ('Janitor');
INSERT INTO POSITIONS (NAME) VALUES ('HR staff');
INSERT INTO POSITIONS (NAME) VALUES ('Head of Department');
INSERT INTO POSITIONS (NAME) VALUES ('Lawyer');
INSERT INTO POSITIONS (NAME) VALUES ('System Architect');

INSERT INTO GRADES (NAME) VALUES ('Trainee');
INSERT INTO GRADES (NAME) VALUES ('Junior');
INSERT INTO GRADES (NAME) VALUES ('Middle');
INSERT INTO GRADES (NAME) VALUES ('Senior');
INSERT INTO GRADES (NAME) VALUES ('Chief');

INSERT INTO DEPARTMENTS (PARENT_ID, NAME, HEAD) VALUES (NULL, 'HR', 1);
INSERT INTO DEPARTMENTS (PARENT_ID, NAME, HEAD) VALUES (1, 'Employee Relations', 2);
INSERT INTO DEPARTMENTS (PARENT_ID, NAME, HEAD) VALUES (1, 'Personnel Management', 3);
INSERT INTO DEPARTMENTS (PARENT_ID, NAME, HEAD) VALUES (NULL, 'Sales', 4);
INSERT INTO DEPARTMENTS (PARENT_ID, NAME, HEAD) VALUES (4, 'Market Research', 5);
INSERT INTO DEPARTMENTS (PARENT_ID, NAME, HEAD) VALUES (4, 'Marketing', 6);
INSERT INTO DEPARTMENTS (PARENT_ID, NAME, HEAD) VALUES (NULL, 'Accounting', 7);
INSERT INTO DEPARTMENTS (PARENT_ID, NAME, HEAD) VALUES (7, 'Accounts and Wages', 8);
INSERT INTO DEPARTMENTS (PARENT_ID, NAME, HEAD) VALUES (7, 'Creditors and Debtors', 9);
INSERT INTO DEPARTMENTS (PARENT_ID, NAME, HEAD) VALUES (NULL, 'IT', 10);
INSERT INTO DEPARTMENTS (PARENT_ID, NAME, HEAD) VALUES (10, 'Development', 11);
INSERT INTO DEPARTMENTS (PARENT_ID, NAME, HEAD) VALUES (10, 'QA', 12);

INSERT INTO EMPLOYEES ("UID", FIRST_NAME, SECOND_NAME, SEX, BIRTH_DATE, DEPARTMENT_ID, POSITION_ID, GRADE_ID, SALARY, FROM_DATE)
VALUES (1, 'Bill', 'Johns', 'M', TO_DATE('09/12/1980', 'MM/DD/YYYY'), 1, 11, 3, 12345, SYSDATE);
INSERT INTO EMPLOYEES ("UID", FIRST_NAME, SECOND_NAME, SEX, BIRTH_DATE, DEPARTMENT_ID, POSITION_ID, GRADE_ID, SALARY, FROM_DATE)
VALUES (2, 'John', 'Doe', 'M', TO_DATE('03/11/1970', 'MM/DD/YYYY'), 2, 11, 3, 12345, SYSDATE);
INSERT INTO EMPLOYEES ("UID", FIRST_NAME, SECOND_NAME, SEX, BIRTH_DATE, DEPARTMENT_ID, POSITION_ID, GRADE_ID, SALARY, FROM_DATE)
VALUES (3, 'Marta', 'Grey', 'F', TO_DATE('05/27/1981', 'MM/DD/YYYY'), 3, 11, 3, 12345, SYSDATE);
INSERT INTO EMPLOYEES ("UID", FIRST_NAME, SECOND_NAME, SEX, BIRTH_DATE, DEPARTMENT_ID, POSITION_ID, GRADE_ID, SALARY, FROM_DATE)
VALUES (4, 'Will', 'Smith', 'M', TO_DATE('01/08/1977', 'MM/DD/YYYY'), 4, 11, 3, 12345, SYSDATE);
INSERT INTO EMPLOYEES ("UID", FIRST_NAME, SECOND_NAME, SEX, BIRTH_DATE, DEPARTMENT_ID, POSITION_ID, GRADE_ID, SALARY, FROM_DATE)
VALUES (5, 'Frank', 'Freeman', 'M', TO_DATE('02/14/1983', 'MM/DD/YYYY'), 5, 11, 3, 12345, SYSDATE);
INSERT INTO EMPLOYEES ("UID", FIRST_NAME, SECOND_NAME, SEX, BIRTH_DATE, DEPARTMENT_ID, POSITION_ID, GRADE_ID, SALARY, FROM_DATE)
VALUES (6, 'Maggie', 'Phillipson', 'F', TO_DATE('07/25/1979', 'MM/DD/YYYY'), 6, 11, 3, 12345, SYSDATE);
INSERT INTO EMPLOYEES ("UID", FIRST_NAME, SECOND_NAME, SEX, BIRTH_DATE, DEPARTMENT_ID, POSITION_ID, GRADE_ID, SALARY, FROM_DATE)
VALUES (7, 'Bart', 'Simpson', 'M', TO_DATE('02/15/1970', 'MM/DD/YYYY'), 7, 11, 3, 12345, SYSDATE);
INSERT INTO EMPLOYEES ("UID", FIRST_NAME, SECOND_NAME, SEX, BIRTH_DATE, DEPARTMENT_ID, POSITION_ID, GRADE_ID, SALARY, FROM_DATE)
VALUES (8, 'Chandler', 'Trump', 'M', TO_DATE('03/17/1990', 'MM/DD/YYYY'), 8, 11, 3, 12345, SYSDATE);
INSERT INTO EMPLOYEES ("UID", FIRST_NAME, SECOND_NAME, SEX, BIRTH_DATE, DEPARTMENT_ID, POSITION_ID, GRADE_ID, SALARY, FROM_DATE)
VALUES (9, 'George', 'Bush', 'M', TO_DATE('10/01/1978', 'MM/DD/YYYY'), 9, 11, 3, 12345, SYSDATE);
INSERT INTO EMPLOYEES ("UID", FIRST_NAME, SECOND_NAME, SEX, BIRTH_DATE, DEPARTMENT_ID, POSITION_ID, GRADE_ID, SALARY, FROM_DATE)
VALUES (10, 'Stew', 'Capito', 'M', TO_DATE('04/20/1988', 'MM/DD/YYYY'), 10, 11, 3, 12345, SYSDATE);
INSERT INTO EMPLOYEES ("UID", FIRST_NAME, SECOND_NAME, SEX, BIRTH_DATE, DEPARTMENT_ID, POSITION_ID, GRADE_ID, SALARY, FROM_DATE)
VALUES (11, 'Helen', 'Thompson', 'F', TO_DATE('06/22/1976', 'MM/DD/YYYY'), 11, 11, 3, 12345, SYSDATE);
INSERT INTO EMPLOYEES ("UID", FIRST_NAME, SECOND_NAME, SEX, BIRTH_DATE, DEPARTMENT_ID, POSITION_ID, GRADE_ID, SALARY, FROM_DATE)
VALUES (12, 'Alexandra', 'McGregor', 'F', TO_DATE('07/29/1971', 'MM/DD/YYYY'), 12, 11, 3, 12345, SYSDATE);

INSERT INTO CERTIFICATES (EMPLOYEE_ID, "DATE", COMPANY, NAME, "NUMBER") VALUES (1, TO_DATE('01/01/2000', 'MM/DD/YYYY'), 'Certificate Company 1', 'Certificate 1', 1);
INSERT INTO CERTIFICATES (EMPLOYEE_ID, "DATE", COMPANY, NAME, "NUMBER") VALUES (1, TO_DATE('01/01/1990', 'MM/DD/YYYY'), 'Certificate Company 2', 'Certificate 2', 2);
INSERT INTO CERTIFICATES (EMPLOYEE_ID, "DATE", COMPANY, NAME, "NUMBER") VALUES (1, TO_DATE('01/01/2001', 'MM/DD/YYYY'), 'Certificate Company 3', 'Certificate 3', 3);
INSERT INTO CERTIFICATES (EMPLOYEE_ID, "DATE", COMPANY, NAME, "NUMBER") VALUES (1, TO_DATE('01/01/1997', 'MM/DD/YYYY'), 'Certificate Company 4', 'Certificate 4', 4);
INSERT INTO CERTIFICATES (EMPLOYEE_ID, "DATE", COMPANY, NAME, "NUMBER") VALUES (1, TO_DATE('01/01/2003', 'MM/DD/YYYY'), 'Certificate Company 5', 'Certificate 5', 5);
INSERT INTO CERTIFICATES (EMPLOYEE_ID, "DATE", COMPANY, NAME, "NUMBER") VALUES (1, TO_DATE('01/01/1999', 'MM/DD/YYYY'), 'Certificate Company 6', 'Certificate 6', 6);
INSERT INTO CERTIFICATES (EMPLOYEE_ID, "DATE", COMPANY, NAME, "NUMBER") VALUES (1, TO_DATE('01/01/1990', 'MM/DD/YYYY'), 'Certificate Company 7', 'Certificate 7', 7);
INSERT INTO CERTIFICATES (EMPLOYEE_ID, "DATE", COMPANY, NAME, "NUMBER") VALUES (1, TO_DATE('01/01/2010', 'MM/DD/YYYY'), 'Certificate Company 8', 'Certificate 8', 8);
INSERT INTO CERTIFICATES (EMPLOYEE_ID, "DATE", COMPANY, NAME, "NUMBER") VALUES (1, TO_DATE('01/01/1998', 'MM/DD/YYYY'), 'Certificate Company 9', 'Certificate 9', 9);
INSERT INTO CERTIFICATES (EMPLOYEE_ID, "DATE", COMPANY, NAME, "NUMBER") VALUES (1, TO_DATE('01/01/2008', 'MM/DD/YYYY'), 'Certificate Company 10', 'Certificate 10', 10);
INSERT INTO CERTIFICATES (EMPLOYEE_ID, "DATE", COMPANY, NAME, "NUMBER") VALUES (1, TO_DATE('01/01/1996', 'MM/DD/YYYY'), 'Certificate Company 11', 'Certificate 11', 11);
INSERT INTO CERTIFICATES (EMPLOYEE_ID, "DATE", COMPANY, NAME, "NUMBER") VALUES (1, TO_DATE('01/01/1991', 'MM/DD/YYYY'), 'Certificate Company 12', 'Certificate 12', 12);
